### ISSUE TITLE
PyPi page looks strange

### ISSUE THREAD

**Issue by guettli** [mvantellingen/django-healthchecks#2]
Hi,

the pypi page of your projects looks strange: https://pypi.python.org/pypi/django_healthchecks

Maybe there is a RST syntax error?

**Comment by mvantellingen** [comment]
Yeah need to fix that :-)

**Comment by mvantellingen** [comment]
Fixed :)

**Comment by guettli** [comment]
The pypi page looks good now. Thank you.
