### ISSUE TITLE
What is the difference between your app and the system checks of django core?

### ISSUE THREAD

**Issue by guettli** [mvantellingen/django-healthchecks#3]
I am interested in your project.

Was is the difference between your project and the system checks of django core?

Related: https://docs.djangoproject.com/en/1.9/topics/checks/

I am looking for a django application that lets my specify things like:

- do check `foo` monday to friday hourly between 8:00 and 18:00.

The times and checks need to be configurable via admin (storing the values in db is preferred).

Is this possible with your app?

**Comment by mvantellingen** [comment]
This application can generate json output which can be used by third party monitoring tools. It doens't handle your use-case. In that case you might want to make a management cmd which you via crontab

**Comment by guettli** [comment]
I see. The scheduler is a second system. Makes sense. Thank you for your reply.
